---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 1m
  values:
    csi:
      enabled: true
    server:
      dev:
        enabled: true
      service:
        type: NodePort
        nodePort: 30000
