apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: tfc-demo
  namespace: default
  labels:
    weave.works/template-type: terraform
  annotations:
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
spec:
  description: Template for creating new EKS clusters.
  renderType: templating
  params:
    - name: CLUSTER_NAME
      description: Name of the cluster.
    - name: CLUSTER_VERSION
      description: Version of the cluster.
      options: ["1.21", "1.22", "1.23", "1.24"]
      default: "1.24"
    - name: AWS_REGION
      description: AWS region to deploy cluster.
      default: us-east-1
    - name: VPC_CIDR
      description: IPv4 cidr range for VPC.
      default: 10.0.0.0/16
    - name: PUBLIC_SUBNET_COUNT
      description: Number of public subnets to create.
      default: "3"
    - name: PRIVATE_SUBNET_COUNT
      description: Number of private subnets to create.
      default: "3"
    - name: DESIRED_SIZE
      description: Desired number of nodes in cluster.
      default: "2"
    - name: MIN_SIZE
      description: Min number of nodes in cluster.
      default: "1"
    - name: MAX_SIZE
      description: Max number of nodes in cluster.
      default: "3"
    - name: CAPACITY_TYPE
      description: Capacity type of nodes in cluster.
      options: ["ON_DEMAND", "SPOT"]
      default: "ON_DEMAND"
    - name: INSTANCE_TYPE
      description: Instance type of nodes in cluster.
      default: "t3.medium"
  resourcetemplates:
    - path: clusters/management/clusters/{{ .template.meta.namespace }}/{{ .params.CLUSTER_NAME }}.yaml
      content:
        - apiVersion: infra.contrib.fluxcd.io/v1alpha1
          kind: Terraform
          metadata:
            name: '{{ .params.CLUSTER_NAME }}-core'
            namespace: flux-system
          spec:
            interval: 1h
            retryInterval: 20s
            path: ./terraform/cluster-templates/core
            approvePlan: auto
            destroyResourcesOnDeletion: false
            writeOutputsToSecret:
              name: '{{ .params.CLUSTER_NAME }}-core-outputs'
            backendConfig:
              disable: true
            cliConfigSecretRef:
              name: tfc-cli-config
            vars:
              - name: cluster_name
                value: '{{ .params.CLUSTER_NAME }}'
              - name: cluster_version
                value: '{{ .params.CLUSTER_VERSION }}'
              - name: region
                value: '{{ .params.AWS_REGION }}'
              - name: vpc_cidr
                value: '{{ .params.VPC_CIDR }}'
              - name: public_subnet_count
                value: '{{ .params.PUBLIC_SUBNET_COUNT }}'
              - name: private_subnet_count
                value: '{{ .params.PRIVATE_SUBNET_COUNT }}'
            sourceRef:
              kind: GitRepository
              name: flux-system
              namespace: flux-system
        - apiVersion: infra.contrib.fluxcd.io/v1alpha1
          kind: Terraform
          metadata:
            name: '{{ .params.CLUSTER_NAME }}-config'
            namespace: flux-system
          spec:
            dependsOn:
              - name: '{{ .params.CLUSTER_NAME }}-core'
            interval: 1h
            retryInterval: 20s
            path: ./cluster-templates/leaf-cluster-config
            approvePlan: auto
            destroyResourcesOnDeletion: false
            backendConfig:
              disable: true
            cliConfigSecretRef:
              name: tfc-cli-config
            vars:
              - name: cluster_name
                value: '{{ .params.CLUSTER_NAME }}'
              - name: region
                value: '{{ .params.AWS_REGION }}'
              - name: desired_size
                value: '{{ .params.DESIRED_SIZE }}'
              - name: min_size
                value: '{{ .params.MIN_SIZE }}'
              - name: max_size
                value: '{{ .params.MAX_SIZE }}'
              - name: capacity_type
                value: '{{ .params.CAPACITY_TYPE }}'
              - name: instance_type
                value: '{{ .params.INSTANCE_TYPE }}'
            sourceRef:
              kind: GitRepository
              name: flux-system
              namespace: flux-system
